--- 
defaultAttemptTitle: "Incorrect convention"
errorCommentIssue: 
  body: "Al parecer los cambios realizados no son los esperados. A continuación puedes encontrar más información al respecto:\\n"
  labels: 
    - bug
errorConventionIssue: 
  body: |-
      La convención de código a seguir:
      - Para los arreglos: `<FIX ID>: <Comentario>`
      - Para los arreglos con conflictos: `<FIX ID>: <Comentario por defecto del merge>`
      
      Igualmente, solo hay 3 fixes a realizar. Al realizar uno y completarlo se creará un issue con las instrucciones a realizar para el siguiente.
      
      Para realizar la corrección del mensaje de commit `git commit --amend` y `git commit push -f`
  title: "Un commit que no sigue la convención de código o FIX a realizar"
errorInvalidIssueNumber: 
  body: "Al parecer los cambios realizados se identificaron con el número de corrección incorrecto."
errorNoIssueOpen: 
  body: "Al parecer el issue del fix asociado no está abierto, pero aún no se cumple con los elementos necesarios. Revisa los issues cerrados y abre de nuevo aquel asociado a:"
  title: "El issue asociado al fix fue cerrado"
fixes: 
  - 
    actions: 
      - 
        data: 
          - 
            title: FIX1
            totalPoints: 100
          - 
            title: "Incorrect convention"
            totalPoints: -5
        type: GRADE
    files: 
      - 
        expectedValues: 
          - 
            attribute: src
            querySelector: "#imagen5"
            type: DOM
            value: ../imagenes/BD5.gif
          - 
            attribute: textContent
            querySelector: "#titulo5"
            type: DOM
            value: "Mi quinta página HTML"
        filename: html/pagina5.html
        ref: refs/heads/fix_1
    nextIssue: 
      body: "Prueba de correcciones finalizada"
      labels: 
        - bug
      number: 2
      title: "FIN de las correcciones"
    title: FIX1
initialIssue: 
  body: |
      ### FIX ID: FIX1 
      
      ### Errores a corregir:
      - pagina5.html.  La imagen y el título de la página no corresponden.
      
      ### Soluciones:
       - En `pagina5.html`, cambiar el link de la imagen a BD5.gif y el texto del título que se encuentra debajo de la imagen por 'Mi quinta página HTML'.
  labels: 
    - bug
  number: 1
  title: "ISSUE 1: Corrección de páginas 5"
multipleAttempts: true
rawFeedback: false
traceAttempts: true
users: 
  - 
    email: disere@email.com
    name: disere
  - 
    email: inds@email.com
    name: inds
  - 
    email: seands@email.com
    name: seands
  - 
    email: erracep@email.com
    name: erracep
  - 
    email: somen@email.com
    name: somen
