---
multipleAttempts: true
traceAttempts: true
defaultAttemptTitle: Incorrect convention
rawFeedback: false
users:
- email: disere@email.com
  name: disere
- email: inds@email.com
  name: inds
- email: seands@email.com
  name: seands
- email: erracep@email.com
  name: erracep
- email: somen@email.com
  name: somen
errorNoIssueOpen:
  title: El issue asociado al arreglo fue cerrado
  body: 'Al parecer el issue del fix asociado no está abierto, pero aún no se cumple
    con los elementos necesarios. Revisa los issues cerrados y abre de nuevo aquel
    asociado a:'
errorConventionIssue:
  title: Un commit que no sigue la convención de código o arreglo a realizar
  body: |-
    La convención de código a seguir: `<Identificador comentario>: <Comentario>`

    Igualmente, solo hay 1 arreglo a realizar. Al realizar cada paso y completarlo se creará un issue con las instrucciones a realizar para continuar.
    
    Para realizar la corrección del mensaje de commit usar `git commit --amend` y `git commit push -f`
errorCommentIssue:
  labels:
  - bug
  body: "Al parecer los cambios realizados no son los esperados. A continuación puedes encontrar más información al respecto: \n"
errorInvalidIssueNumber:
  body: Los cambios realizados no lograron identificarse como los requeridos por el issue actualmente abierto. Puede que se haya generado un conflicto entre ramas, que
    el commit realizado tenga una identificación inválida o no se siguieron las indicaciones respecto a la rama donde se deben realizar los cambios.
initialIssue:
  number: 1
  labels:
  - bug
  title: 'ISSUE 1: Agregar nueva receta'
  body: "### Identificador la acción: STEP1 \n\n ## Acciones a realizar: 
    \n- Cree la rama 'receta_1' a partir de la rama 'desarrollo'.
    \n- Agregue la receta colombiana Arroz con Coco (arroz_coco.html) en la ruta 'recetas/Colombia'. 
    \n- Agregue la imagen de la receta (arroz_coco.jpg) en la ruta '/imagenes'.
    \n- Incluya la receta en el archivo 'index.html'" 
fixes:
- title: STEP1
  files:
  - filename: recetas/Colombia/arroz_coco.html
    ref: refs/heads/receta_1
    expectedValues:
    - type: DOM
      querySelector: "#titulo1"
      attribute: textContent
      value: Arroz con coco
    - type: DOM
      querySelector: "#imagen1"
      attribute: src
      value: "../imagenes/arroz_coco.jpg"
  - filename: recetas/index.html
    ref: refs/heads/receta_1
    expectedValues:
    - type: DOM
      querySelector: "#colombia2"
      attribute: textContent
      value: Arroz con coco
  - filename: imagenes/arroz_coco.jpg
    ref: refs/heads/receta_1
  nextIssue:
    number: 2
    labels:
    - bug
    title: 'ISSUE 2: Merge de los cambios con desarrollo'
    body: "### Identificador del error o acción: MERGE1 \n\n ## Acciones a realizar: 
    \n- Hacer merge de la rama 'receta_1' con la rama 'desarrollo'
    \n **NOTA:** Recuerde que para la identificación de la acción requerida es necesario
    establecer como comentario del commit de merge algo como 'MERGE1: Merge de los cambios'."
  actions:
  - type: DOM
    data:
      pullRequest:
        pullBase: desarrollo
        pullHead: error_receta_1
        createPull: false
        mergePull: true
        mergeMessage: Merge automático
      files:
      - filename: recetas/Colombia/ajiaco.html
        valueChanges:
        - querySelector: "#titulo1"
          attribute: textContent
          value: ""
- title: MERGE1
  files:
  - filename: recetas/Colombia/arroz_coco.html
    ref: refs/heads/desarrollo
    expectedValues:
    - type: DOM
      querySelector: "#titulo1"
      attribute: textContent
      value: Arroz con coco
    - type: DOM
      querySelector: "#imagen1"
      attribute: src
      value: "../../imagenes/arroz_coco.jpg"
  - filename: recetas/index.html
    ref: refs/heads/desarrollo
    expectedValues:
    - type: DOM
      querySelector: "#colombia2"
      attribute: textContent
      value: Arroz con coco
  - filename: imagenes/arroz_coco.jpg
    ref: refs/heads/desarrollo
  nextIssue:
    number: 3
    labels:
    - bug
    title: 'ISSUE 3: Crear una rama de lanzamiento'
    body: "### Identificador la acción: STEP2 \n\n###Acciones a realizar: 
    \n- Cree la rama 'release' a partir de la rama 'desarrollo'.
    \n- Verifique que las recetas 'Ajiaco' y 'Arroz con coco' cuenten con los elementos básicos (título, imagen, ingredientes y preparación). 
    \n De no ser así, realice los ajustes correspondientes sobre la rama." 
  actions:
  - type: DOM
    data:
      pullRequest:
        pullBase: release
        pullHead: error_receta_2
        createPull: false
        mergePull: true
        mergeMessage: Merge automático
      files:
      - filename: recetas/Colombia/arroz_coco.html
        valueChanges:
        - querySelector: "#titulo1"
          attribute: textContent
          value: ""
        - querySelector: "#imagen1"
          attribute: src
          value: ""
- title: STEP2
  files:
  - filename: recetas/Colombia/arroz_coco.html
    ref: refs/heads/release
    expectedValues:
    - type: DOM
      querySelector: "#titulo1"
      attribute: textContent
      value: Arroz con coco
    - type: DOM
      querySelector: "#imagen1"
      attribute: src
      value: "../imagenes/arroz_coco.jpg"
  - filename: recetas/Colombia/ajiaco.html
    ref: refs/heads/release
    expectedValues:
    - type: DOM
      querySelector: "#titulo1"
      attribute: textContent
      value: Ajiaco
  nextIssue:
    number: 4
    title: Final del ejercicio
    labels: []
    body: |-
      **Ha llegago al final del ejercicio y su código esta listo para integrarse con master. ¡Buen trabajo!**
  actions:
  - type: GRADE
    data:
    - title: STEP1
      totalPoints: 50
    - title: MERGE1
      totalPoints: 50
    - title: Incorrect convention
      totalPoints: -5
